export enum MessageLabel {
    INVITATION = 'INVITATION',
    MARKETING = 'MARKETING',
    API_FAILURE_ALERT = 'API_FAILURE_ALERT',
    FEEDBACK_FOR_ISTEM = 'FEEDBACK_FOR_ISTEM',
    REQUEST_STATUS_UPDATE = 'REQUEST_STATUS_UPDATE',
    ESCALATION = 'ESCALATION',
    AUTHENTICATION = 'AUTHENTICATION',
    REQUEST_SERVICE_UPGRADE = 'REQUEST_SERVICE_UPGRADE',
    JOB_APPLICATION = 'JOB_APPLICATION',
    MENTORSHIP = 'MENTORSHIP',
    AFC_FAILURE = 'AFC_FAILURE',
    ISTEM_ADMIN_FLOW = "ISTEM_ADMIN_FLOW",
    ISTEM_TEAM_NOTIFICATION = "ISTEM_TEAM_NOTIFICATION",
    HACKATHON = "HACKATHON",
    REPORT = "REPORT",
    VC_FAILURE = "VC_FAILURE",
}

export enum MessageStatus {
    INITIATED = "INITIATED",
    SENT = "SENT",
    READ = "READ",
}

