export enum FileProcessAssociations {
AFC_INPUT = "AFC/INPUT",
AFC_OUTPUT = "AFC/OUTPUT",
AFC_REMEDIATION = "AFC/REMEDIATION",
VC_INPUT = "VC/INPUT",
VC_OUTPUT = "VC/OUTPUT",
VC_REMEDIATION = "VC/REMEDIATION",
VC_CUSTOM_MODEL_TRAINING_DATA = "VC/CUSTOM_MODEL_TRAINING_DATA",
COMMUNITY_JOB_RESUME = "COMMUNITY/JOB/RESUME"
}
