export enum AFCRequestStatus {
    REQUEST_INITIATED = "REQUEST_INITIATED",
    OCR_REQUESTED = "OCR_REQUESTED",
    OCR_REQUEST_ACCEPTED = "OCR_REQUEST_ACCEPTED",
    OCR_REQUEST_REJECTED = "OCR_REQUEST_REJECTED",
    OCR_COMPLETED = "OCR_COMPLETED",
    OCR_FAILED = "OCR_FAILED",
    OCR_SKIPPED = "OCR_SKIPPED",
    FORMATTING_REQUESTED = "FORMATTING_REQUESTED",
    FORMATTING_COMPLETED = "FORMATTING_COMPLETED",
    FORMATTING_FAILED = "FORMATTING_FAILED",
    ESCALATION_REQUESTED = "ESCALATION_REQUESTED",
    ESCALATION_RESOLVED = "ESCALATION_RESOLVED",
    RETRY_REQUESTED = "RETRY_REQUESTED",
    RESOLVED_FILE_USED = "RESOLVED_FILE_USED",
}

export enum AFCRequestOutputFormat {
    PDF = "PDF",
    TEXT = "TXT",
    WORD = "DOCX",
    MP3 = "MP3",
    HTML = "HTML",
}

export enum AFCTriggerer {
    USER = "user",
    VC_MODEL = "vc_model",
}

export enum DocType {
    MATH = "MATH",
    NONMATH = "NONMATH",
}

