export enum VideoExtractionType {
    CAPTION = "CAPTION",
    OCR = "OCR",
    OCR_CAPTION = "OCR_CAPTION",
}

export enum CaptionOutputFormat {
    SRT = "srt",
    TXT = "txt",
}

export enum VCRequestStatus {
    INITIATED = "INITIATED",
    INDEXING_REQUESTED = "INDEXING_REQUESTED",
    INDEXING_REQUEST_FAILED = "INDEXING_REQUEST_FAILED",
    INDEXING_SKIPPED = "INDEXING_SKIPPED",
    CALLBACK_RECEIVED = "CALLBACK_RECEIVED",
    INDEXING_API_FAILED = "INDEXING_API_FAILED",
    INSIGHT_REQUESTED = "INSIGHT_REQUESTED",
    INSIGHT_FAILED = "INSIGHT_FAILED",
    COMPLETED = "COMPLETED",
    ESCALATION_REQUESTED = "ESCALATION_REQUESTED",
    ESCALATION_RESOLVED = "ESCALATION_RESOLVED",
    RETRY_REQUESTED = "RETRY_REQUESTED",
    RESOLVED_FILE_USED = "RESOLVED_FILE_USED",
}

