export  enum UserType {
    I_STEM = "I_STEM",
    UNIVERSITY = "UNIVERSITY",
    BUSINESS = "BUSINESS",
    VOLUNTEER = "VOLUNTEER",
    ADMIN = "ADMIN",
}

export enum OAuthProvider {
    GOOGLE = "GOOGLE",
    FACEBOOK = "FACEBOOK",
    TWITTER = "TWITTER",
    GITHUB = "GITHUB",
    PASSWORD = "PASSWORD",
}

export enum OtherUserRoles {
    MENTOR = "MENTOR",
    UNKNOWN = "UNKNOWN",
}

export enum UserRoleEnum {
    USER = "USER",
    ADMIN = "ADMIN",
}

export enum UserStatusEnum {
    USER_CREATED = "USER_CREATED",
    VERIFY_USER_MAIL_SENT = "VERIFY_USER_MAIL_SENT",
    USER_VERIFIED = "USER_VERIFIED",
    ROLE_UPGRADE_REQUEST_RECIEVED = "ROLE_UPGRADE_REQUEST_RECIEVED",
    ROLE_UPGRADE_REQUEST_MAIL_SENT = "ROLE_UPGRADE_REQUEST_MAIL_SENT",
    ROLE_UPGRADE_REQUEST_COMPLETE = "ROLE_UPGRADE_REQUEST_COMPLETE",
}

export const enum ServiceRoleEnum {
    REGULAR = "REGULAR",
    PREMIUM = "PREMIUM",
}

export enum ColorThemes {
    BLACKWHITE = "BLACKWHITE",
    WHITEBLACK = "WHITEBLACK",
    GREENWHITE = "GREENWHITE",
    REDWHITE = "REDWHITE",
    YELLOWBLACK = "YELLOWBLACK",
    YELLOWBLUE = "YELLOWBLUE",
}
export enum FontThemes {
    FONTM = "FONTM",
    FONTL = "FONTL",
    FONTXL = "FONTXL",
}
